apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickstack:8123
    isDefault: true

    jsonData:
      host: clickstack
      port: 8123
      protocol: http
      username: grafana

    secureJsonData:
      password: "123"